version: '3'

name: integration
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:debug-remote
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.development
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
      - 9229:9229 # debugger
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:6.2.3-alpine
    networks:
      - app-network

networks:
  app-network:
