version: '3'

name: nestjs-graphql-schemafirst
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:debug-remote
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
      - 9229:9229 # debugger
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:6.2.3-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./infra/docker/redis.conf:/usr/local/etc/redis/redis.conf # to simulate redis cluster with user credentials and roles
    ports:
      - 6379:6379
    networks:
      - app-network

  bull-monitor:
    container_name: bull-monitor
    image: tiagoboeing/bull-board:latest
    restart: always
    ports:
      - 4000:4000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_PREFIX: nestjs-schema-first
      QUEUE_NAMES: 'notifications-queue'
    networks:
      - app-network
    depends_on:
      - redis

networks:
  app-network:
