apiVersion: v1
kind: Service
metadata:
  name: integration-service
spec:
  type: LoadBalancer
  selector:
    app: integration
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: integration-service
      protocol: TCP
      port: 3000
      targetPort: 3000
