name: Build and test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          standalone: true
          version: 9.7.1
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Tests
        run: pnpm test:cov
      